name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --env prod --routes docker.${{ secrets.DOMAIN }},gcr.${{ secrets.DOMAIN }},ghcr.${{ secrets.DOMAIN }},quay.${{ secrets.DOMAIN }}
