name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: "deploy --env prod \
            --routes docker.${{ secrets.DOMAIN }} \
            --routes gcr.${{ secrets.DOMAIN }} \
            --routes ghcr.${{ secrets.DOMAIN }} \
            --routes quay.${{ secrets.DOMAIN }}"
